version: "3.9"
services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: db_linktic
      MYSQL_USER: admin
      MYSQL_PASSWORD: password*
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  products-service:
    build: ./products-service
    container_name: products-service
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: admin
      DB_PASS: password*
      DB_NAME: db_linktic
    depends_on:
      - mysql
    ports:
      - "3000:3000"

  inventory-service:
    build: ./inventory-service
    container_name: inventory-service
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: admin
      DB_PASS: password*
      DB_NAME: db_linktic
      PRODUCTS_URL: http://products-service:3000
      PRODUCTS_API_KEY: supersecretkey
    depends_on:
      - mysql
      - products-service
    ports:
      - "3001:3000"

volumes:
  mysql_data:
